
# site settings

title: Ricardo Hernández Osorio
description: Jekyll theme for my projects
taglong: Jekyll theme
tagshort: Jekyll

# author settings

author:
  name: Ricardo Hernández Osorio
  email: ricardo.hdz.o@outlook.com

# social media links

social:
  facebook: username
  github: username
  instagram: username
  linkedin: username
  stackoverflow: 0000000/username
  twitter: username

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

autopages:
  enabled: false

